export interface Experience {
  title: string;
  company: string;
  period: string;
  bullets: string[];
}

export interface Education {
  degree: string;
  institution: string;
  period: string;
  score: string;
}

export interface PersonalInfo {
  name: string;
  title: string;
  email: string;
  phone: string;
  location: string;
  github: string;
}

export const personalInfo: PersonalInfo = {
  name: "Sumanth Tatipamula",
  title: "Software Developer",
  email: "sumanthtatipamula123@gmail.com",
  phone: "(+91) 7981662597",
  location: "Hyderabad, India",
  github: "sumanthtatipamula",
};

export const experiences: Experience[] = [
  {
    title: "Software Engineer",
    company: "ServiceNow",
    period: "Nov 2023 – Current",
    bullets: [
      "Currently involved in the UX components team, actively enhancing the LIST component.",
      "Designed and implemented infinite scroll functionality in gallery view for enhanced user experience on the list.",
      "Created up/down arrow navigation in quick forms, allowing seamless traversal between records in the list.",
      "Implemented list calculations feature which enables user to see aggregate values for the field.",
      "Introduced live-list functionality that enables users to view real-time updates to any record.",
    ],
  },
  {
    title: "Platform Software Engineer",
    company: "Oracle",
    period: "Sept 2020 – Oct 2023",
    bullets: [
      "Created several backend map-reduce scripts to handle bulk data operations.",
      "Developed several front-end pages using suitescript, an internal JS framework.",
      "Built a single-page application using the UIF framework, which is based on React JS.",
      "Analyzed and configured product metrics for all team projects.",
    ],
  },
  {
    title: "SDE Intern",
    company: "Amazon",
    period: "Jan 2020 – Jul 2020",
    bullets: [
      "Developed an application that sends notifications about pickup start times to shippers.",
      "Implemented CI/CD pipelines for various stages of the service.",
      "Automated the creation of AWS resources using the cloudformation template.",
      "Documented high level and low level designs.",
      "Created a checkstyles file so that all team projects follow similar coding standards.",
    ],
  },
  {
    title: "BackEnd Developer",
    company: "Coral Innovations Private Limited",
    period: "Jan 2019 – Mar 2019",
    bullets: [
      "Designed and developed a dashboard application using MongoDB and Node.js to gain insights into data generated by mobile application.",
      "Managed Heroku deployments and set up MongoDB database based on application needs.",
    ],
  },
];

export const education: Education[] = [
  {
    degree: "BE in Computer Science",
    institution: "Vasavi College of Engineering",
    period: "2016 – 2020",
    score: "CGPA: 9.15",
  },
  {
    degree: "Intermediate",
    institution: "Narayana Junior College",
    period: "2014 – 2016",
    score: "Per: 97.4%",
  },
  {
    degree: "Class X in SSC",
    institution: "Narayana E-Techno School",
    period: "2014",
    score: "CGPA: 9.5",
  },
];

export const skills: string[] = [
  "C/C++",
  "Java",
  "SQL",
  "Git",
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Node.js",
  "Bootstrap",
];

export const achievements: string[] = [
  "Received 3 Llama awards in Q1 2024, Q4 2024, Q1 2025",
  "The TrailBlazer Award in Oracle 2022",
  "Secured first place in Android development Hackathon conducted by Real Page organization 2019",
  "Member of Google Developer Student Club 2019",
  "Won second prize in tech quiz conducted by CSI Telangana State Level Student Convention at MVSR College Of Engineering 2018",
];

export const certifications: string[] = [
  "AWS Certified Cloud Practitioner",
  "Azure AI Fundamentals (AI-900)",
  "Database Management Systems - Nptel - IIT Kharagpur",
  "Real Time Operating Systems - Nptel - IIT Kharagpur",
  "Programming, Data Structures And Algorithms - Nptel - IIT Madras",
  "Front-End Web UI Frameworks and Tools: Bootstrap 4 - Coursera",
  "Front-End Web Development with React - Coursera",
];
